Feature/create animals table
Ayokunnumi1/vet-clinic pull request #1
Opened 2023-10-23 19:55 UTC by Ayokunnumi1

These are the functionalities implemented in this branch;
- Microverse curriculum database template was used,
- A database named vet_clinic was created,
- A table named animals with 6 columns was created,
- Data was inserted into the animals table,
- Eight queries were written and eight screenshots were taken.
![1](https://github.com/Ayokunnumi1/vet-clinic/assets/130077023/f064a8f0-ae5f-4d4a-a39a-dc45bad9be2c)
![Screenshot 2023-10-23 004854](https://github.com/Ayokunnumi1/vet-clinic/assets/130077023/ef7a72db-813e-4b75-a0cf-7872b55d7b60)
![Screenshot 2023-10-23 004922](https://github.com/Ayokunnumi1/vet-clinic/assets/130077023/1bbbb8f7-511f-4b75-9f40-f05480f079b4)
![Screenshot 2023-10-23 005006](https://github.com/Ayokunnumi1/vet-clinic/assets/130077023/c0fd8c1c-ad34-4338-841b-0e9181fbdc98)
![Screenshot 2023-10-23 005050](https://github.com/Ayokunnumi1/vet-clinic/assets/130077023/191fe503-0866-4d73-af03-61165c28ccc1)
![Screenshot 2023-10-23 005156](https://github.com/Ayokunnumi1/vet-clinic/assets/130077023/850881b9-9705-429c-b0d3-970fa6d13fc6)
![Screenshot 2023-10-23 005320](https://github.com/Ayokunnumi1/vet-clinic/assets/130077023/ff15fcce-728a-4ac5-a28a-6a26713f93e9)
![Screenshot 2023-10-23 005550](https://github.com/Ayokunnumi1/vet-clinic/assets/130077023/8f6f29d9-d348-4621-89dc-4160472169a2)

2023-10-23 19:58 UTC, franclobo reviewed
Hi @Ayokunnumi1, 

# Invalid Code Review Request
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a professional README file, please edit your file before submitting it again.

![image](https://github.com/Ayokunnumi1/vet-clinic/assets/58642949/3f2535d8-c44e-4fb3-b298-0c168579a821)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-10-23 21:18 UTC, Shedrack-Sunday requested changes
Hello @Ayokunnumi1    👋 

# CHANGES REQUIRED ♻️

Impressive work on the project so far👏
You've done extremely well so far in this project,  However, there are some adjustments you need to make to move to the next project. 💯

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use of GitHub features ✔️   
- Nice work with SQL queries✔️
- Kudus adding the screenshots to the PR effectively     ✔️  

# - Required Changes  🌵  

- [ ] Kindly include the right path for your License by adding it to the root of your project so it leads to the right section. Presently its failing  


# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing really improves your application.



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-10-23 21:18 UTC, Shedrack-Sunday commented on README.md
> +This project is [MIT](/LICENSE) licensed.
- [ ] Kindly include the License file to the root of the project so the path is clickable 👍

2023-10-24 11:18 UTC, Efiamotu-1 approved these changes
Hi @Ayokunnumi1, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED 🕺🥳 

![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)

## Highlights :dart: 
* Correct Gitflow :heavy_check_mark: 
* Good PR summary :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-24 11:20 UTC, merged